#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: genBrcmProfile.sh <input file> <output file> [sdk version]"
	echo -e "\tinput file is OpenWRT configuration file in TOPDIR"
	echo -e "\toutput file is Broadcom's Profile"
	echo -e "\tsdk version is optional parameter, it should be '414L03' or '412L08' or others"
	exit -1
fi

if  [ ! -e $1 ]; then
	echo "File '$1' not found!"
	exit -2
fi

if [ -n "$3" ]; then
BRCM_VER=$3
else
BRCM_VER=
fi

echo -e "#\n# Automatically generated by make menuconfig + genBrcmProfile.sh : don't edit\n#\n" > $2

# 1. using 'grep' to filter the BRCM configurations which prefix is "CONFIG_BRCMSDK_"
# 2. using 'sed' to remove prefix 'CONFIG_BRCMSDK_
grep "CONFIG_BRCMSDK${BRCM_VER}_" $1 | sed "s/^\# CONFIG_BRCMSDK${BRCM_VER}_/# /; s/^CONFIG_BRCMSDK${BRCM_VER}_//" >> $2

# To collect options which need to remove quotes
OPT_RM_QUOTES=`grep "CONFIG_BRCM${BRCM_VER}_RM_QUOTES_" $1 | sed "s/^CONFIG_BRCM${BRCM_VER}_RM_QUOTES_//; s/=y//"`

# remove quotes
if [ -n "$OPT_RM_QUOTES" ]; then
	# Build a sed script to remove quotes in a single pass
	# Note: Assumes option names are alphanumeric identifiers (no special regex chars)
	sed_script=""
	for i in $OPT_RM_QUOTES; do
		sed_script="${sed_script}/\\b$i\\b/s/\"//g;"
	done
	sed -i "$sed_script" $2
fi
